name: CI HW-2
on:
  # Triggers the workflow on push for hw-2 branch or pull request for main branch events 
  push:
    branches: [ hw-2 ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Сборка однопроцессоной реализации
  serial-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy-12 clang-format-12
      - name: CMake with option for tests
        run: |
          cd hw-2
          mkdir build
          cd build
          cmake -DTESTS=ON -DWITH_STATIC_CHECKS=ON ..
      - name: Code Style
        run: |
          cd hw-2/build 
          make clangformat
      - name: Make
        run: |
          cd hw-2/build 
          make
  serial-test:
    runs-on: ubuntu-latest
    needs: [serial-build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy-12 clang-format-12
      - name: CMake with option for tests
        run: |
          cd hw-2
          mkdir build
          cd build
          cmake -DTESTS=ON ..
      - name: Make
        run: |
          cd hw-2/build 
          make
      - name: TESTS
        run: |
          cd hw-2/build 
          ./tests/test_kmeans
  # Сборка многопроцессоной реализации
  multiprocess-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy-12 clang-format-12
      - name: CMake with option for tests
        run: |
          cd hw-2
          mkdir build
          cd build
          cmake -DTESTS=ON -DMULTIPROCESS=ON -DWITH_STATIC_CHECKS=ON ..
      - name: Code Style
        run: |
          cd hw-2/build 
          make clangformat
      - name: Make
        run: |
          cd hw-2/build 
          make -j8
  multiprocess-test:
    runs-on: ubuntu-latest
    needs: [multiprocess-build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy-12 clang-format-12
      - name: CMake with option for tests
        run: |
          cd hw-2
          mkdir build
          cd build
          cmake -DTESTS=ON -DMULTIPROCESS=ON ..
      - name: Make
        run: |
          cd hw-2/build 
          make
      - name: TESTS
        run: |
          cd hw-2/build 
          ./tests/test_kmeans